# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4024198c2eba62c3369b8633da796e8232089bd15a28ed22cb779178a86967606b1ada3713e3ce538b711f3507d0b8bd2d9f2f6e50bb7a572593e2e27b91bba3

test:
  secret_key_base: 31b6c5bdf1868e9bed180822186854486c42e39ecbc1597f605271c516b9114d49eaf3ea73aae196bc7fbadadc31b9588b4980d6de21655abb51d4fc9a3c8c66

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
